name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run prettier

  ubuntu:
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      HARAKA_COVERAGE: 1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps
      - run: npm test

  windows:
    needs: [lint]
    runs-on: windows-latest
    env:
      HARAKA_COVERAGE: 1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps
      - run: npm test
