name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  ubuntu:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps
      - run: npm run test:coverage

  windows:
    needs: [lint]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - run: npm cache clean --force
      - run: npm install --legacy-peer-deps
      - run: npm run test:coverage
